entity: mogfn
method: grid
metric:
  goal: maximize
  name: HV with zero ref
parameters:
  const_temp:
    values:
      - 4
      - 8
      - 16
  dirichlet_param:
    values:
      - 1.0
      - 1.5
      - 2.0
      - 2.5
  global_batch_size:
    values:
      - 32
      - 64
  learning_rate:
    values:
      - 0.0005
      - 0.0001
      - 0.00005
  num_emb:
    values:
      - 32
      - 64
      - 128
  num_layers:
    distribution: int_uniform
    max: 6
    min: 3
program: seh_frag_moo.py
project: fragments