const_temp: 96
dirichlet_param: 0.1
global_batch_size: 256
learning_rate: 0.0005
num_emb: 128
num_layers: 6
seed:
  - 90
  - 100
  - 110
  - 120
array_job: True
baseline_training: False
use_wandb: False
log_dir: 'logs/seh_moo_alpha_0.1/'
rew_type: "convex"
project: "fragments"

