bind_mounts:
  # This allows you to retain the settings in jupyter lab after a session
  - host_path: /mnt/ps/home/CORP/sharath.raparthy/cfgs/notebook/
    container_path: /run/determined/workdir/.jupyter/lab/user-settings
  # This mounts your home folder, make sure to open notebooks here or they won't be saved
  - host_path: /mnt/ps/home/CORP/sharath.raparthy/
    container_path: /run/determined/workdir/home/
  - host_path: /mnt/bh1/data/
    container_path: /data
  # This is where models trained on Determined are stored
  - host_path: /mnt/bh1/scratch/det_checkpoints
    container_path: /mnt/bh1/scratch/det_checkpoints
    read_only: true
  - host_path: /mnt/bh1/scratch/sandbox/sharath.raparthy/
    container_path: /sandbox
environment:
  image: gcr.io/eng-infrastructure/gflownet:libxrender
  add_capabilities:
    - IPC_LOCK
  force_pull_image: false
  environment_variables:
    - TORCH_HOME=/torch_home
    - LD_LIBRARY_PATH=/usr/local/mpi/lib/:$LD_LIBRARY_PATH
resources:
  resource_pool: dgx-pool # This requests one gpu
  agent_label: ampere
  priority: 1
