name: qm9_mxmnet_gap
description: MXMNet target (beta~U[0,32])
data:
  h5_path: /data/chem/qm9/qm9.h5
  path: /data/chem/qm9/qm9.xyz.tar
hyperparameters:
  qm9_h5_path: /data/chem/qm9/qm9.h5
  adam_eps: 1e-8
  bootstrap_own_reward: False
  clip_grad_type: norm
  clip_grad_param: 10
  global_batch_size: 64
  illegal_action_logreward: -50
  learning_rate: 1e-4
  momentum: 0.9
  num_data_loader_workers: 8
  num_emb: 128
    # type: categorical
    # vals:
    #   - 128
    #   - 256
  num_layers: 4
    # type: categorical
    # vals:
    #   - 3
    #   - 5
  reward_loss_multiplier: 1
  random_action_prob: 0.001
  sampling_tau: 0
  temperature_sample_dist: uniform
  temperature_dist_params: (0.2, 32)
  tb_epsilon: None
  weight_decay: 1e-8
  lr_decay: 100000
  Z_lr_decay: 100000
  #temperature_sample_dist: gamma
  #temperature_dist_params: (1.5, 1.5)
  #temperature_sample_dist: beta
  #temperature_dist_params: (1.25, 2)
searcher:
  name: single
  metric: validation_loss
  max_length:
      batches: 100000
  smaller_is_better: true
min_validation_period:
  batches: 500
entrypoint: qm9:QM9Trial
checkpoint_policy: best
checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 0
  host_path: /mnt/bh1/scratch/det_checkpoints
  type: shared_fs
bind_mounts:
  - host_path: /mnt/ps/home/CORP/emmanuel.bengio/
    container_path: /run/determined/workdir/home/
  - host_path: /mnt/bh1/data/
    container_path: /data
  - host_path: /mnt/bh1/scratch/emmanuel.bengio/
    container_path: /scratch/
environment:
  image: determinedai/environments:cuda-11.3-pytorch-1.10-lightning-1.5-tf-2.8-gpu-0.17.12
  add_capabilities:
    - IPC_LOCK
  force_pull_image: false
resources:
  resource_pool: dgx-pool
  agent_label: ampere
  priority: 1
  slots_per_trial: 1
#profiling:
#  enabled: true
