name:  Qm9 Full Sweep
description: Experiments Sweep
data:
  h5_path: /data/chem/qm9/qm9_new.h5
  path: /data/chem/qm9/qm9.xyz.tar
hyperparameters:
  log_dir: /scratch/qm9_logs/
  qm9_h5_path: /data/chem/qm9/qm9_new.h5
  adam_eps: 1e-8
  bootstrap_own_reward: False
  clip_grad_type: norm
  clip_grad_param: 10
  global_batch_size: 64
  illegal_action_logreward: -50
  learning_rate: 1e-4
  momentum: 0.9
  num_data_loader_workers: 8
  is_specific_target: False
  specific_target: ["QED"]
  seed: 100
  num_emb:
    type: categorical
    vals:
      # - 128
      - 256
  num_layers:
     type: categorical
     vals:
       - 3
       # - 4
       # - 5
  reward_loss_multiplier: 2
  random_action_prob: 0.001
  sampling_tau: 0.99
  temperature_sample_dist:
      type: categorical
      vals:
          - uniform
          - gamma
          - const
  uniform_temperature_dist_params: (0.2, 32)
  gamma_temperature_dist_params: (32, 2)
  beta_temperature_dist_params: (2, 1)
#      type: categorical
#      vals:
#          - (2, 1)
#          - (2, 2)
#          - (2, 3)
#          - (3, 3)
  const_temp : 32
#       type: categorical
#       vals:
#           - 8
#           - 4
  temperature_max_min: (0, 32)
  reward_transform:  unit+95p
  number_of_objectives:
      type: categorical
      vals:
          # - 1
          - 2
          - 3
          - 4
  targets: ["gap", "logP", "QED", "molecular_weight"]
  tb_epsilon: None
  weight_decay: 1e-8
  lr_decay: 100000
  Z_lr_decay: 100000
  #temperature_sample_dist: gamma
  #temperature_dist_params: (1.5, 1.5)
  #temperature_sample_dist: beta
  #temperature_dist_params: (1.25, 2)
  number_test_samples: 50
  k_value: 10
  hsri_epsilon: 0.4
  num_test_preferences: 120
searcher:
  name: grid
  metric: r2_dist
  max_length:
      batches: 100000
  smaller_is_better: true
min_validation_period:
  batches: 200
perform_initial_validation: True
entrypoint: qm9:QM9Trial
checkpoint_policy: best
checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 0
  host_path: /mnt/ps/home/CORP/emmanuel.bengio/sandbox/det_logs/
  type: shared_fs
bind_mounts:
  - host_path: /mnt/ps/home/CORP/emmanuel.bengio/rs/tmp_sharath_gfn/
    container_path: /run/determined/workdir/home/
  - host_path: /mnt/bh1/data/
    container_path: /data
  - host_path: /mnt/bh1/scratch/emmanuel.bengio/
    container_path: /scratch
environment:
  # image: determinedai/environments:cuda-11.3-pytorch-1.10-lightning-1.5-tf-2.8-gpu-0.17.12
  image: gcr.io/eng-infrastructure/gflownet:libxrender
  add_capabilities:
    - IPC_LOCK
  force_pull_image: false
resources:
  resource_pool: dgx-pool
  agent_label: ampere
  priority: 1
  slots_per_trial: 1
# profiling:
#  enabled: true


