name:  Test Qm9 Gamma (2, 2) Online Experiments
description: Experiments Sweep
data:
  h5_path: /data/chem/qm9/qm9.h5
  path: /data/chem/qm9/qm9.xyz.tar
hyperparameters:
  qm9_h5_path: /data/chem/qm9/qm9.h5
  adam_eps: 1e-8
  bootstrap_own_reward: False
  clip_grad_type: norm
  clip_grad_param: 10
  global_batch_size: 64
  illegal_action_logreward: -50
  learning_rate: 1e-4
  momentum: 0.9
  num_data_loader_workers: 8
  num_emb: 128
    # type: categorical
    # vals:
    #   - 128
    #   - 256
  num_layers: 4
    # type: categorical
    # vals:
    #   - 3
    #   - 5
  reward_loss_multiplier: 2
  random_action_prob: 0.001
  sampling_tau: 0.99
  temperature_sample_dist: gamma
      # type: categorical
      # vals:
      #     - uniform
          # - gamma
  temperature_dist_params: (2, 2)
  const_temp : 8
      # type: categorical
      # vals:
          # - (0.2, 32)
          # - (2, 1)
          # - (1, 1)
  temperature_max_min: (0, 32)
  reward_transform:  unit+95p
  number_of_objectives:
      type: categorical
      vals:
          - 1
          - 2
          - 3
          - 4
  targets: ["gap", "logP", "QED", "molecular_weight"]
  tb_epsilon: None
  weight_decay: 1e-8
  lr_decay: 100000
  Z_lr_decay: 100000
  #temperature_sample_dist: gamma
  #temperature_dist_params: (1.5, 1.5)
  #temperature_sample_dist: beta
  #temperature_dist_params: (1.25, 2)
searcher:
  name: grid
  metric: offline_loss
  max_length:
      batches: 100000
  smaller_is_better: true
min_validation_period:
  batches: 500
entrypoint: qm9:QM9Trial
checkpoint_policy: best
checkpoint_storage:
  save_trial_best: 1
  save_trial_latest: 1
  save_experiment_best: 0
  host_path: /mnt/ps/home/CORP/sharath.raparthy/sandbox/qm9_results/
  type: shared_fs
bind_mounts:
  - host_path: /mnt/ps/home/CORP/sharath.raparthy/
    container_path: /run/determined/workdir/home/
  - host_path: /mnt/bh1/data/
    container_path: /data
  - host_path: /mnt/ps/home/CORP/sharath.raparthy/sandbox/
    container_path: /sandbox/
environment:
  image: determinedai/environments:cuda-11.3-pytorch-1.10-lightning-1.5-tf-2.8-gpu-0.17.12
  add_capabilities:
    - IPC_LOCK
  force_pull_image: false
resources:
  resource_pool: dgx-pool
  agent_label: ampere
  priority: 1
  slots_per_trial: 1
# profiling:
#  enabled: true
